### ISSUE TITLE
Difficulties to run service from VSCode on Windows

### ISSUE THREAD

**Issue by CodeShakingSheep** [Louis3797/express-ts-auth-service#8]
Hi,

I had to adopt the scripts for using them on Windows:
`"dev": "tsc --project ./tsconfig.json --watch &SET NODE_ENV=development nodemon --trace-warnings ./dist/index.js",
"build": "tsc --project ./tsconfig.json",
"start": "yarn run build && SET NODE_ENV=production node --trace-warnings ./dist/index.js",
"watch": "tsc --project ./tsconfig.json --watch",`

Note the removal of '' and replacement of NODE_ENV with SET NODE_ENV. Still, when I run `yarn start` I get this output and the process terminates after a few seconds.

`yarn run v1.22.19
warning ..\..\..\..\package.json: No license field
$ yarn run build && SET NODE_ENV=production node --trace-warnings ./dist/index.js
warning ..\..\..\..\package.json: No license field
$ tsc --project ./tsconfig.json
Done in 3.44s.`

When I run `yarn dev` the process stays active. However, I cannot reach the server on the configured URL (SERVER_URL and PORT in .env file). This is the output:

[01:14:01] Starting compilation in watch mode...

[01:14:05] Found 0 errors. Watching for file changes.

I am still new to TS development. My environment is as follows:
- Windows 10
- VS Code
- node v16.15.0
- yarn 1.22.19
- tsc 5.0.2

What am I missing here? Thank you.

**Comment by Louis3797** [comment]
The `SERVER_URL` variable is used to dynamically generate the links to reset the password and check the email, so the URL doesn't need to be hardcoded.  You might want to say that in a comment in the env.example. 

If you set the .env `PORT` variable to say 4040 the server will run on `http://localhost:4040`

**Comment by CakraDarma** [comment]
@CodeShakingSheep I have same issue, have you resolved it?

**Comment by Louis3797** [comment]
Maybe try to add [cross-env](https://www.npmjs.com/package/cross-env)
You need to add the cross-env command in the package.json script
 ```json
 "scripts": {
    "dev": "tsc --project './tsconfig.build.json' --watch && cross-env NODE_ENV=development nodemon --trace-warnings ./dist/index.js",
    ...
    "start": "yarn run build && cross-env NODE_ENV=production node --trace-warnings ./dist/index.js",
    ...
  },
```

I hope that fixes it

**Comment by Louis3797** [comment]
i added cross-env hopefully its fixed
